### PR TITLE
src: using ubi8/nodejs-12 instead of nodeshift/centos7-s2i-nodejs

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by helio-frota** [comment]
@lholmquist ubi8/nodes-12 is available :+1: 
/me already tested locally in `crc` and it is working fine.

**Comment by lholmquist** [comment]
missed the applicaiton.yaml,  https://github.com/nodeshift-starters/nodejs-rest-http/blob/master/.openshiftio/application.yaml#L54

**Comment by helio-frota** [comment]
Impressive... 

```
11:08 $ rg centos7
✘-1 ~/Desktop/examples/nodejs-rest-http [ubi8 L|✚ 2] 
```

`rg` means ripgrep command , kind of grep alternative...

after that I noticed that rg don't search on hidden files by default ... 

It should be

```
rg centos7 --hidden
```

Thanks for the review, I'm going to update that :+1:

**Comment by lholmquist** [comment]
i noticed the node version in the ubi version is 12.4.0,  LTS node is 12.13.0, do we know when that will be updated.

I think think the current centos7-s2i-nodejs 12.x is 12.12.0

**Comment by helio-frota** [comment]
yeah, I noticed that also.
I have no idea when they plan to release a new version, we can take a look on that.

**Review by lholmquist — APPROVED** [review]
This looks good.  i'm still concerned about the verson of Node 12,  but once that gets updated, these changes will get the latest updates anyway

**Pull request merged**
